# Generated by Django 5.1.4 on 2024-12-09 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moshtari',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری'},
        ),
        migrations.CreateModel(
            name='TypeMoshtari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='نام')),
                ('moshtari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afrad.moshtari', verbose_name='مشتری')),
            ],
        ),
    ]
