# Generated by Django 5.1.4 on 2024-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afrad', '0002_alter_moshtari_options_typemoshtari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typemoshtari',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AddField(
            model_name='moshtari',
            name='behkar',
            field=models.IntegerField(blank=True, null=True, verbose_name='بدهکار'),
        ),
        migrations.AddField(
            model_name='moshtari',
            name='variz',
            field=models.BooleanField(default=False, verbose_name='اتمام پرداخت'),
        ),
        migrations.AddField(
            model_name='moshtari',
            name='varizshode',
            field=models.IntegerField(blank=True, null=True, verbose_name='واریزی'),
        ),
        migrations.AlterField(
            model_name='moshtari',
            name='desc',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='کپشن'),
        ),
    ]
